// 24
const districtList = [
    {label: 'Tất cả địa điểm', value: 'all'},
    {label: 'Quận 1', value: '1'},
    {label: 'Quận 2', value: '2'},
    {label: 'Quận 3', value: '3'},
    {label: 'Quận 4', value: '4'},
    {label: 'Quận 5', value: '5'},
    {label: 'Quận 6', value: '6'},
    {label: 'Quận 7', value: '7'},
    {label: 'Quận 8', value: '8'},
    {label: 'Quận 9', value: '9'},
    {label: 'Quận 10', value: '10'},
    {label: 'Quận 11', value: '11'},
    {label: 'Quận 12', value: '12'},
    {label: 'Thủ Đức', value: '13'},
    {label: 'Gò Vấp', value: '14'},
    {label: 'Bình Thạnh', value: '15'},
    {label: 'Tân Bình', value: '16'},
    {label: 'Tân Phú', value: '17'},
    {label: 'Phú Nhuận', value: '18'},
    {label: 'Bình Tân', value: '19'},
    {label: 'Củ Chi', value: '20'},
    {label: 'Hóc Môn', value: '21'},
    {label: 'Bình Chánh', value: '22'},
    {label: 'Nhà Bè', value: '23'},
    {label: 'Cần Giờ', value: '24'},
  ];

  export default districtList;