import { createActions } from 'redux-actions'


const {
  getReviewByUser,
  getReviewByUserSuccess,
  getReviewByUserFail,
  getReviewById,
  getReviewByIdSuccess,
  getReviewByIdFail,
  postReview,
  postReviewSuccess,
  postReviewFail,
  getReviewsOfBook,
  getReviewsOfBookSuccess,
  getReviewsOfBookFail,
  toggleLikeReview,
  toggleLikeReviewSuccess,
  toggleLikeReviewFail,
  toggleLikeSingleReview,
  toggleLikeSingleReviewSuccess,
  toggleLikeSingleReviewFail,
  getAllReviews,
  getAllReviewsSuccess,
  getAllReviewsFail,
  getReviewLite,
  getReviewLiteSuccess,
  getReviewLiteFail,
} = createActions(
  'GET_REVIEW_BY_USER',
  'GET_REVIEW_BY_USER_SUCCESS',
  'GET_REVIEW_BY_USER_FAIL',
  'GET_REVIEW_BY_ID',
  'GET_REVIEW_BY_ID_SUCCESS',
  'GET_REVIEW_BY_ID_FAIL',
  'POST_REVIEW',
  'POST_REVIEW_SUCCESS',
  'POST_REVIEW_FAIL',
  'GET_REVIEWS_OF_BOOK',
  'GET_REVIEWS_OF_BOOK_SUCCESS',
  'GET_REVIEWS_OF_BOOK_FAIL',
  'TOGGLE_LIKE_REVIEW',
  'TOGGLE_LIKE_REVIEW_SUCCESS',
  'TOGGLE_LIKE_REVIEW_FAIL',
  'TOGGLE_LIKE_SINGLE_REVIEW',
  'TOGGLE_LIKE_SINGLE_REVIEW_SUCCESS',
  'TOGGLE_LIKE_SINGLE_REVIEW_FAIL',
  'GET_ALL_REVIEWS',
  'GET_ALL_REVIEWS_SUCCESS',
  'GET_ALL_REVIEWS_FAIL',
  'GET_REVIEW_LITE',
  'GET_REVIEW_LITE_SUCCESS',
  'GET_REVIEW_LITE_FAIL',
)



export {
  getReviewByUser,
  getReviewByUserSuccess,
  getReviewByUserFail,
  getReviewById,
  getReviewByIdSuccess,
  getReviewByIdFail,
  postReview,
  postReviewSuccess,
  postReviewFail,
  getReviewsOfBook,
  getReviewsOfBookSuccess,
  getReviewsOfBookFail,
  toggleLikeReview,
  toggleLikeReviewSuccess,
  toggleLikeReviewFail,
  toggleLikeSingleReview,
  toggleLikeSingleReviewSuccess,
  toggleLikeSingleReviewFail,
  getAllReviews,
  getAllReviewsSuccess,
  getAllReviewsFail,
  getReviewLite,
  getReviewLiteSuccess,
  getReviewLiteFail,
}